benchmarks:
  - benchmark 1
  - benchmark 2
data_dir: 'data'

# Hooks
hooks:
  pre_batch: 'scripts/pre_batch.py'
  pre_run: 'scripts/pre_run.py'
  run: 'scripts/run.py'
  post_run: 'scripts/post_run.py'
  collect_logs: 'scripts/collect_logs.py'
  post_batch: 'scripts/post_batch.py'
  get_metric: 'scripts/get_metric.py'
